In [1]:
import pandas as pd
from pathlib import Path
src_path = Path.cwd().parents[1]
src_path

PosixPath('/data/home/shubi/Readability/src')

In [2]:
# save xlsx as csv
df = pd.read_excel(src_path / 'data/CLEAR/CLEAR_corpus_final.xlsx')
df

,ID,Author,Title,Anthology,URL,Pub Year,Categ,Sub Cat,Lexile Band,Location,...,BT_easiness,s.e.,Flesch-Reading-Ease,Flesch-Kincaid-Grade-Level,Automated Readability Index,SMOG Readability,New Dale-Chall Readability Formula,CAREC,CAREC_M,CML2RI
0,400,Carolyn Wells,Patty's Suitors,NaN,http://www.gutenberg.org/cache/epub/5631/pg563...,1914.0,Lit,NaN,900,mid,...,-0.340259,0.464009,81.70,5.95,7.37,8.0,6.55,0.12102,0.11952,12.097815
1,401,Carolyn Wells,Two Little Women on a Holiday,NaN,http://www.gutenberg.org/cache/epub/5893/pg589...,1917.0,Lit,NaN,700,mid,...,-0.315372,0.480805,80.26,4.86,4.16,7.0,6.25,0.04921,0.04921,22.550179
2,402,Carolyn Wells,Patty Blossom,NaN,http://www.gutenberg.org/cache/epub/20945/pg20...,1917.0,Lit,NaN,900,mid,...,-0.580118,0.476676,79.04,6.03,5.81,9.0,7.31,0.10172,0.09724,18.125279
3,403,CHARLES KINGSLEY,THE WATER-BABIES\nA Fairy Tale for a Land-Baby,NaN,http://www.gutenberg.org/files/25564/25564-h/2...,1863.0,Lit,NaN,1300,mid,...,-1.785965,0.526599,44.77,20.51,24.87,12.0,8.56,0.07491,0.08856,10.959460
4,404,Charles Kingsley,HOW THE ARGONAUTS WERE DRIVEN INTO THE UNKNOWN...,The Heroes\n or Greek Fairy Tales for my...,http://www.gutenberg.org/files/677/677-h/677-h...,1889.0,Lit,NaN,1300,mid,...,-1.054013,0.450007,68.07,12.06,15.47,8.0,7.00,0.06356,0.08798,3.195960
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4719,8027,wikijunior,Bugs/Monarch butterfly,"""Wikijunior\n",https://en.wikibooks.org/wiki/Wikijunior:Bugs/...,2019.0,Info,Science,410L-600L,start,...,0.423388,0.511439,87.37,3.59,4.37,7.0,6.71,0.13576,0.12908,19.271483
4720,8028,wikijunior,Bugs/Walking Stick,"""Wikijunior\n",https://en.wikibooks.org/wiki/Wikijunior:Bugs/...,2020.0,Info,Science,610L-800L,start,...,-0.614142,0.475506,85.42,4.02,4.32,7.0,7.62,0.08258,0.05378,15.814468
4721,8029,wikijunior,Bugs/Black Widow,Wikijunior\n,https://en.wikibooks.org/wiki/Wikijunior:Bugs/...,2020.0,Info,Science,610L-800L,start,...,0.310336,0.508939,81.36,4.60,5.32,8.0,6.92,0.10992,0.08300,22.731214
4722,8030,wikijunior,Solids,Wikijunior\n,https://en.wikibooks.org/wiki/Geometry_for_Ele...,2014.0,Info,Science,610L-800L,start,...,-0.215279,0.514128,75.83,5.89,5.84,9.0,7.74,0.18951,0.19583,16.386932
4723,8031,wikijunior,Anials,Wikijunior\n,https://en.wikibooks.org/wiki/Wikijunior:Biolo...,2018.0,Info,Science,610L-800L,start,...,0.300779,0.512379,63.07,7.23,6.91,10.0,6.80,0.20880,0.20880,14.830202

In [3]:
df[['ID', 'BT_easiness', 'Excerpt']]

        ID  BT_easiness                                            Excerpt
0      400    -0.340259  When the young people returned to the ballroom...
1      401    -0.315372  All through dinner time, Mrs. Fayre was somewh...
2      402    -0.580118  As Roger had predicted, the snow departed as q...
3      403    -1.785965  Mr. Grimes was to come up next morning to Sir ...
4      404    -1.054013  And outside before the palace a great garden w...
...    ...          ...                                                ...
4719  8027     0.423388  The name Monarch means “king”. An adult Monarc...
4720  8028    -0.614142  Walking Sticks are long, thin, and slow-moving...
4721  8029     0.310336  A Black Widow is a shiny black spider. It has ...
4722  8030    -0.215279  Solids are shapes that you can actually touch....
4723  8031     0.300779  Animals are made of many cells. They eat thing...

[4724 rows x 3 columns]

In [4]:
# replace \n with space
df['Excerpt'] = df['Excerpt'].str.replace('\n', ' ')
df[['ID', 'BT_easiness', 'Excerpt']]
# rename column Excerpt to text, BT_easiness to label
df.rename(columns={'Excerpt': 'text', 'BT_easiness': 'label'}, inplace=True)
# replace double space with single space
df['text'] = df['text'].str.replace('  ', ' ')
df[['ID', 'label', 'text', 'Google WC', 'Sentence Count', 'Paragraphs']]

,ID,label,text,Google WC,Sentence Count,Paragraphs
0,400,-0.340259,When the young people returned to the ballroom...,174,11,6
1,401,-0.315372,"All through dinner time, Mrs. Fayre was somewh...",164,15,6
2,402,-0.580118,"As Roger had predicted, the snow departed as q...",162,11,5
3,403,-1.785965,Mr. Grimes was to come up next morning to Sir ...,159,3,1
4,404,-1.054013,And outside before the palace a great garden w...,163,5,2
...,...,...,...,...,...,...
4719,8027,0.423388,The name Monarch means “king”. An adult Monarc...,171,17,3
4720,8028,-0.614142,"Walking Sticks are long, thin, and slow-moving...",176,17,3
4721,8029,0.310336,A Black Widow is a shiny black spider. It has ...,178,17,4
4722,8030,-0.215279,Solids are shapes that you can actually touch....,148,12,3
4723,8031,0.300779,Animals are made of many cells. They eat thing...,143,13,4

In [5]:
df[['ID', 'label', 'text', 'Google WC', 'Sentence Count', 'Paragraphs']].to_csv(src_path / 'data/CLEAR/CLEAR_corpus_final.csv', index=False)