In [1]:
import pandas as pd
from pathlib import Path
from nltk.tokenize import sent_tokenize
import nltk
import string
from wordfreq import word_frequency
from src.utils.textual_utils import count_sentences


# Download tokenizer (if not already done)
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     /data/home/gkeren/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [2]:
src_path = Path.cwd().parents[1]
src_path

PosixPath('/data/home/gkeren/Readability/src')

In [3]:
# parag_metrics_path = src_path / Path("readability_metrics/data/paragraphs_metrics_cleaned.csv")
parag_metrics_path = src_path / Path("Alignment_Sentences/data/paragraphs_df_cleaned.csv")

data_parags = pd.read_csv(parag_metrics_path)


# data_parags['sentence_count_nltk'] = data_parags['text'].apply(lambda x: len(sent_tokenize(x)))
# data_parags['n_sentences'] = data_parags['text'].apply(count_sentences)

# data_parags['n_words_no_punct'] = data_parags['text'].apply(lambda x: len(''.join(char for char in x if char not in string.punctuation).split()))
data_parags['n_words'] = data_parags['text'].apply(lambda x: len((x).split()))

# data_parags['sum_word_length'] = data_parags['text'].apply(lambda x: sum([len(word.strip(string.punctuation)) for word in x.split()]))
# data_parags['sum_raw_wordfreq'] = data_parags['text'].apply(lambda x: sum([word_frequency(word, lang="en") * 1e4 for word in x.split()]))


print(f"number of words adv:{data_parags[data_parags['level'] == 'Adv']['n_words'].sum()}")
print(f"number of words ele:{data_parags[data_parags['level'] == 'Ele']['n_words'].sum()}")

number of words adv:19427
number of words ele:15737

In [4]:
data_parags[data_parags['text'].str.contains("Latin")]

,Unnamed: 0,unique_paragraph_id,text,level,text_id,n_words
149,149,2_4_Adv_2,The US-based International Union of Pure and A...,Adv,2_4_2,84

In [6]:
data_parags[data_parags['text'].str.contains("Latin")]['text'].values[0]

"The US-based International Union of Pure and Applied Chemistry (IUPAC), the global organization that governs chemical nomenclature, terminology and measurement, verified the elements on 30 December, 2015 after poring over studies dating back to 2004. The scientists who found them must now come up with formal names to replace the clunky Latin-based placeholders - ununtrium, ununpentium, ununseptium and ununoctium - which reflect their atomic numbers, 113, 115, 117, and 118. The atomic number is the number of protons found in an element's atomic nucleus."

In [20]:
data_parags[data_parags['level'] == 'Adv'].sort_values(by='n_words', ascending=False)[120:]

,Unnamed: 0,unique_paragraph_id,text,level,text_id,n_words
218,218,3_10_Adv_3,"The brown beer bottle, which had been in the w...",Adv,3_10_3,100
90,90,1_8_Adv_5,UK Sport could not say if a disproportionately...,Adv,1_8_5,99
0,0,1_10_Adv_1,"Agios Efstratios is so remote, so forgotten by...",Adv,1_10_1,98
182,182,2_7_Adv_3,"""The Occupy Wall Street movement was a good on...",Adv,2_7_3,97
151,151,2_4_Adv_4,When elements 114 and 116 were assigned formal...,Adv,2_4_4,94
197,197,2_8_Adv_6,The popular ice-cream shop features in a docum...,Adv,2_8_6,94
262,262,3_4_Adv_5,That fear of being ostracized at work is being...,Adv,3_4_5,93
17,17,1_1_Adv_4,One challenge is creating high-definition scan...,Adv,1_1_4,91
217,217,3_10_Adv_2,"""It was very surprising,"" Angela Erdmann, 62, ...",Adv,3_10_2,90
1,1,1_10_Adv_2,"But, because the island still runs on cash, th...",Adv,1_10_2,89
99,99,1_9_Adv_4,But it isn't just students who would benefit f...,Adv,1_9_4,89
96,96,1_9_Adv_1,"Lots of us know we are sleep-deprived, but ima...",Adv,1_9_1,88
205,205,2_9_Adv_2,South American Indians have chewed coca leaves...,Adv,2_9_2,88
192,192,2_8_Adv_1,"From all across Rwanda, and even parts of neig...",Adv,2_8_1,88
54,54,1_4_Adv_5,Part of this is simply that air travel is inhe...,Adv,1_4_5,88
308,308,3_8_Adv_5,The meteorite over Chelyabinsk arrived less th...,Adv,3_8_5,88
173,173,2_6_Adv_2,"Viennese-born Helena Hartlauer, 32, said she w...",Adv,2_6_2,86
16,16,1_1_Adv_3,Google says that the principal aim of the proj...,Adv,1_1_3,86
70,70,1_6_Adv_1,DNA taken from the wisdom tooth of a European ...,Adv,1_6_1,86
221,221,3_10_Adv_6,The message and the bottle will be on display ...,Adv,3_10_6,85
149,149,2_4_Adv_2,The US-based International Union of Pure and A...,Adv,2_4_2,84
133,133,2_2_Adv_6,"He claims Poland's new government, elected in ...",Adv,2_2_6,84
180,180,2_7_Adv_1,Clay Cockrell is sitting in his office at Colu...,Adv,2_7_1,83
148,148,2_4_Adv_1,Such is the lot of the modern-day chemist: you...,Adv,2_4_1,82
40,40,1_3_Adv_1,"They call him the Robin Hood of the banks, a m...",Adv,1_3_1,81
316,316,3_9_Adv_1,The small space is set up to look like a class...,Adv,3_9_1,81
64,64,1_5_Adv_5,One thing to emerge from the Downing Street me...,Adv,1_5_5,81
174,174,2_6_Adv_3,US cities perform relatively poorly in the stu...,Adv,2_6_3,79
278,278,3_6_Adv_3,Electric bikes are different from motorcycles ...,Adv,3_6_3,77
41,41,1_3_Adv_2,"From 2006 to 2008, Duran took out 68 commercia...",Adv,1_3_2,76
229,229,3_1_Adv_2,As engineers put the finishing touches to Noor...,Adv,3_1_2,75
18,18,1_1_Adv_5,But the prospect of driverless cars replacing ...,Adv,1_1_5,74
164,164,2_5_Adv_3,The polygraph was created in 1921 by policeman...,Adv,2_5_3,72
60,60,1_5_Adv_1,"Illegal downloading is a kind of ""moral squalo...",Adv,1_5_1,72
98,98,1_9_Adv_3,He says it's not as simple as persuading teena...,Adv,1_9_3,71
282,282,3_6_Adv_7,"""Accell has great expectations about e-bikes i...",Adv,3_6_7,71
216,216,3_10_Adv_1,Angela Erdmann never knew her grandfather. He ...,Adv,3_10_1,71
239,239,3_2_Adv_2,Increasing prosperity in Asia has pushed up pr...,Adv,3_2_2,70
33,33,1_2_Adv_6,"Uta Frith, who studies autism at University Co...",Adv,1_2_6,67
153,153,2_4_Adv_6,"Along with new names, the scientists must prop...",Adv,2_4_6,67
277,277,3_6_Adv_2,The US is an outlier when it comes to electric...,Adv,3_6_2,61
131,131,2_2_Adv_4,The Polish government pays compensation for li...,Adv,2_2_4,56

In [12]:
data_parags[data_parags['level'] == 'Adv'].sort_values(by='n_words', ascending=False).to_csv('debug_n_words_adv.csv', index=False)

In [15]:
data_parags.iloc[204]

Unnamed: 0                                                           204
unique_paragraph_id                                            2_9_Adv_1
text                   A major international disagreement with wide-r...
level                                                                Adv
text_id                                                            2_9_1
n_words                                                              101
Name: 204, dtype: object

In [15]:
data_parags[data_parags['unique_paragraph_id'] == '2_7_Adv_5']

,Unnamed: 0,unique_paragraph_id,text,level,text_id,n_words
184,184,2_7_Adv_5,"In the US, over the last three decades, the nu...",Adv,2_7_5,154

In [ ]:
text_a = data_parags[data_parags['unique_paragraph_id'] == '2_7_Adv_5']['text'].values[0]
text_b =

'In the US, over the last three decades, the number of extremely wealthy people has been climbing. According to research from Spectrem Group, in 2014, the number of US households with $1m or more in assets - excluding the value of their primary home - increased by 500,000 to 10.1m. In 2007, that number was 9.2m. Households worth $5m or more reached 1.3m and 142,000 households are now worth $25m or more. Since the 2008 financial crisis, the income gap has expanded and the situation "has gotten worse for the wealthy," Cockrell said. The main reason? Not knowing if your friends are friends with you or your money. "Someone else who is also a billionaire - they don\'t want anything from you. Never being able to trust your friendships with people of different means, I think that is difficult," said Cockrell. "As the gap has widened, the rich have become more and more isolated."'

### not like onestop QA

In [ ]:
text_a = data_parags.iloc[204]['text']
text_b = """'major international disagreement with wide-ranging implications for global drugs policy has erupted over the right of Bolivia's indigenous Indian tribes to chew coca leaves, the principal ingredient in cocaine. Bolivia has obtained a special exemption from the 1961 Single Convention on Narcotic Drugs, the framework that governs international drugs policy, allowing its indigenous people to chew the leaves. Bolivia had argued that the convention was in opposition to its new constitution, adopted in 2009, which obliges it to "protect native and ancestral coca as cultural patrimony" and maintains that coca "in its natural state ... is not a dangerous narcotic."'"""
text_b = text_b[:]

In [ ]:
text_a[:]

'A major international disagreement with wide-ranging implications for global drugs policy has erupted over the right of Bolivia\'s indigenous Indian tribes to chew coca leaves, the principal ingredient in cocaine. Bolivia has obtained a special exemption from the 1961 Single Convention on Narcotic Drugs, the framework that governs international drugs policy, allowing its indigenous people to chew the leaves. Bolivia had argued that the convention was in opposition to its new constitution, adopted in 2009, which obliges it to "protect native and ancestral coca as cultural patrimony" and maintains that coca "in its natural state ... is not a dangerous narcotic."'

In [23]:
text_b[0:]

'\'major international disagreement with wide-ranging implications for global drugs policy has erupted over the right of Bolivia\'s indigenous Indian tribes to chew coca leaves, the principal ingredient in cocaine. Bolivia has obtained a special exemption from the 1961 Single Convention on Narcotic Drugs, the framework that governs international drugs policy, allowing its indigenous people to chew the leaves. Bolivia had argued that the convention was in opposition to its new constitution, adopted in 2009, which obliges it to "protect native and ancestral coca as cultural patrimony" and maintains that coca "in its natural state ... is not a dangerous narcotic."\''

In [ ]:
text_a = data_parags.iloc[204]['text']
text_b = """'major international disagreement with wide-ranging implications for global drugs policy has erupted over the right of Bolivia's indigenous Indian tribes to chew coca leaves, the principal ingredient in cocaine. Bolivia has obtained a special exemption from the 1961 Single Convention on Narcotic Drugs, the framework that governs international drugs policy, allowing its indigenous people to chew the leaves. Bolivia had argued that the convention was in opposition to its new constitution, adopted in 2009, which obliges it to "protect native and ancestral coca as cultural patrimony" and maintains that coca "in its natural state ... is not a dangerous narcotic."'"""