## Results for section 3.4 Surprisal as a Readability Measure

"Importantly, the increases are significantly
smaller than in the direct prediction setting (p < 0.001 in all cases, assessed using the
model_perplexity:evaluation_method interaction term in the model P earson_corr ∼
model_perplexity ∗ evaluation_method). In Appendix 11 Figure A12, we obtain similar
results for passages."

## !! make sure you reran this analysis before you look at the results below
src/Correlations/analysis/ppl_trend/test_ppl_trend.py

In [10]:
import pandas as pd

df = pd.read_csv("/data/home/gkeren/Readability/src/Correlations/analysis/ppl_trend/test_ppl_trend_L1_and_L2_FirstReading_paragraph.csv")
# transpose for better readability
df.T

                                            0              1             2
comp_r                               0.719251       0.583915      0.366484
comp_p                                    0.0            0.0      0.002897
log_comp_r                           0.781776       0.629908      0.406306
log_comp_p                                0.0            0.0      0.000864
ppl_coef                             0.002775       0.002359     -0.000013
ppl_coef_p                           0.000108       0.000003      0.979272
ppl_EvalMethod_coef                  0.003333       0.000393      0.003553
ppl_EvalMethod_coef_p                0.000825       0.543528      0.000007
mean_result                          0.323822       0.319618       0.36003
n_values                                   64             64            64
pred_col                      mean_nonzero_TF  SkipRateTotal  RegRateTotal
level_type                       all and diff   all and diff  all and diff
comp_p_symbol                             ***            ***            **
log_comp_p_symbol                         ***            ***           ***
ppl_coef_p_symbol                         ***            ***            ns
ppl_EvalMethod_coef_p_symbol              ***             ns           ***

In [11]:
# transpose for better readability
df[['pred_col', 'ppl_EvalMethod_coef', 'ppl_EvalMethod_coef_p_symbol']]

          pred_col  ppl_EvalMethod_coef ppl_EvalMethod_coef_p_symbol
0  mean_nonzero_TF             0.003333                          ***
1    SkipRateTotal             0.000393                           ns
2     RegRateTotal             0.003553                          ***

In [8]:
df = pd.read_csv("/data/home/gkeren/Readability/src/Correlations/analysis/ppl_trend/test_ppl_trend_L1_and_L2_FirstReading_sentence.csv")
# transpose for better readability
df[['pred_col', 'ppl_EvalMethod_coef', 'ppl_EvalMethod_coef_p_symbol']]

          pred_col  ppl_EvalMethod_coef ppl_EvalMethod_coef_p_symbol
0  mean_nonzero_TF             0.003563                          ***
1    SkipRateTotal             0.003005                          ***
2     RegRateTotal             0.002295                          ***